using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using ChopChopGames.UGM.GoogleSheetTable;
using UnityEditor;
using UnityEngine;

namespace ChopChopGames.UGM.GoogleSheetTable.EditorTools
{
    public static class AccessorGenerator
    {
        // 사용자 데이터로 분리. 다른 위치를 원하면 이 상수 또는 GoogleSheetConfig.outputFolder를 활용.
        public const string OutputPath = "Assets/_UserData/Generated/GoogleSheetAccessors.generated.cs";

        public static void Generate(GoogleSheetConfig config)
        {
            if (config == null) return;
            if (config.spreadSheets == null || config.spreadSheets.Count == 0)
            {
                EditorUtility.DisplayDialog("생성 불가", "정의된 SpreadSheet가 없습니다.", "확인");
                return;
            }

            var spreadSheetsForGen = new List<(string name, string fieldName, string className, List<SheetGenInfo> sheets)>();
            var usedSpreadSheetFields = new HashSet<string>(StringComparer.Ordinal);

            foreach (var ss in config.spreadSheets)
            {
                if (ss == null || string.IsNullOrEmpty(ss.name)) continue;

                var ssField = SanitizeIdentifier(ss.name);
                if (!usedSpreadSheetFields.Add(ssField))
                {
                    Debug.LogWarning($"[GoogleSheet] SpreadSheet 이름 충돌(sanitized): '{ss.name}' → '{ssField}'. 중복 항목 건너뜀.");
                    continue;
                }

                var sheets = new List<SheetGenInfo>();
                var usedSheetFields = new HashSet<string>(StringComparer.Ordinal);

                foreach (var entry in ss.sheets ?? new List<GoogleSheetConfig.SheetEntry>())
                {
                    if (entry == null || string.IsNullOrEmpty(entry.tableName)) continue;
                    if (string.IsNullOrEmpty(entry.rowTypeName)) continue;

                    var rowType = Type.GetType(entry.rowTypeName);
                    if (rowType == null)
                    {
                        Debug.LogWarning($"[GoogleSheet] '{ss.name}/{entry.tableName}' rowType 해석 실패: {entry.rowTypeName}. 건너뜀.");
                        continue;
                    }

                    var attr = rowType.GetCustomAttribute<GoogleSheetRowAttribute>(false);
                    var preferredName = !string.IsNullOrEmpty(attr?.TableName) ? attr.TableName : entry.tableName;
                    var sheetField = SanitizeIdentifier(preferredName);

                    if (!usedSheetFields.Add(sheetField))
                    {
                        Debug.LogWarning($"[GoogleSheet] '{ss.name}' 안에서 sheet 필드명 충돌: '{preferredName}' → '{sheetField}'. 중복 항목 건너뜀.");
                        continue;
                    }

                    var typeText = BuildStructureTypeText(entry, rowType);
                    if (typeText == null)
                    {
                        Debug.LogWarning($"[GoogleSheet] '{ss.name}/{entry.tableName}' 구조 타입 추론 실패. keyColumn 또는 dataStructure 설정을 확인하세요. 건너뜀.");
                        continue;
                    }

                    sheets.Add(new SheetGenInfo
                    {
                        Entry = entry,
                        RowType = rowType,
                        SheetField = sheetField,
                        TypeText = typeText,
                    });
                }

                var ssClass = ssField + "SpreadSheet";
                spreadSheetsForGen.Add((ss.name, ssField, ssClass, sheets));
            }

            // === 새 출력 템플릿: partial class 확장 대신 별도 static class GoogleSheetAccessors ===
            // Manager가 RegisterOnLoad로 등록한 콜백을 LoadAll 끝에 호출하는 구조.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// AUTO-GENERATED by ChopChopGames/GoogleSheet/Generate Accessors. DO NOT EDIT MANUALLY.");
            sb.AppendLine("// Re-run the menu after changing Config to regenerate.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using ChopChopGames.UGM.GoogleSheetTable;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace ChopChopGames.UGM.GoogleSheetTable.Generated");
            sb.AppendLine("{");

            foreach (var ss in spreadSheetsForGen)
            {
                sb.AppendLine($"    public class {ss.className}");
                sb.AppendLine("    {");
                foreach (var s in ss.sheets)
                    sb.AppendLine($"        public {s.TypeText} {s.SheetField};");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("    public static class GoogleSheetAccessors");
            sb.AppendLine("    {");
            foreach (var ss in spreadSheetsForGen)
                sb.AppendLine($"        public static {ss.className} {ss.fieldName} {{ get; private set; }} = new {ss.className}();");

            sb.AppendLine();
            sb.AppendLine("        // 게임 시작 시 1회 자동 등록. Manager.LoadAll 완료 후 Initialize가 호출됨.");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine("            GoogleSheetTableManager.RegisterOnLoad(Initialize);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static void Initialize(GoogleSheetTableManager manager)");
            sb.AppendLine("        {");
            foreach (var ss in spreadSheetsForGen)
            {
                foreach (var s in ss.sheets)
                {
                    var line = BuildAssignmentLine(ss.fieldName, s, ss.name);
                    if (line != null) sb.AppendLine($"            {line}");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var folder = Path.GetDirectoryName(OutputPath).Replace('\\', '/');
            GoogleSheetDownloader.EnsureFolder(folder);
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.ImportAsset(OutputPath);
            AssetDatabase.Refresh();

            int totalSheets = 0;
            foreach (var ss in spreadSheetsForGen) totalSheets += ss.sheets.Count;
            Debug.Log($"[GoogleSheet] Accessors 생성 완료: {OutputPath} (SpreadSheets: {spreadSheetsForGen.Count}, Sheets: {totalSheets})");
        }

        private class SheetGenInfo
        {
            public GoogleSheetConfig.SheetEntry Entry;
            public Type RowType;
            public string SheetField;
            public string TypeText;
        }

        private static string BuildStructureTypeText(GoogleSheetConfig.SheetEntry entry, Type rowType)
        {
            var rowName = TypeText(rowType);
            switch (entry.dataStructure)
            {
                case DataStructure.List:
                    return $"IReadOnlyList<{rowName}>";

                case DataStructure.Dictionary:
                {
                    if (string.IsNullOrEmpty(entry.keyColumn)) return null;
                    var keyType = TypedTableParser.GetMemberType(rowType, entry.keyColumn);
                    if (keyType == null) return null;
                    return $"IReadOnlyDictionary<{TypeText(keyType)}, {rowName}>";
                }

                case DataStructure.DictionaryOfList:
                {
                    if (string.IsNullOrEmpty(entry.keyColumn)) return null;
                    var keyType = TypedTableParser.GetMemberType(rowType, entry.keyColumn);
                    if (keyType == null) return null;
                    return $"IReadOnlyDictionary<{TypeText(keyType)}, List<{rowName}>>";
                }
            }
            return null;
        }

        private static string BuildAssignmentLine(string ssField, SheetGenInfo s, string spreadSheetName)
        {
            var rowName = TypeText(s.RowType);
            var ssLit = EscapeStringLiteral(spreadSheetName);
            var tableLit = EscapeStringLiteral(s.Entry.tableName);

            switch (s.Entry.dataStructure)
            {
                case DataStructure.List:
                    return $"{ssField}.{s.SheetField} = manager.GetList<{rowName}>(\"{ssLit}\", \"{tableLit}\");";

                case DataStructure.Dictionary:
                {
                    var keyType = TypedTableParser.GetMemberType(s.RowType, s.Entry.keyColumn);
                    if (keyType == null) return null;
                    return $"{ssField}.{s.SheetField} = manager.GetDict<{TypeText(keyType)}, {rowName}>(\"{ssLit}\", \"{tableLit}\");";
                }

                case DataStructure.DictionaryOfList:
                {
                    var keyType = TypedTableParser.GetMemberType(s.RowType, s.Entry.keyColumn);
                    if (keyType == null) return null;
                    return $"{ssField}.{s.SheetField} = manager.GetGroupedDict<{TypeText(keyType)}, {rowName}>(\"{ssLit}\", \"{tableLit}\");";
                }
            }
            return null;
        }

        private static string TypeText(Type t)
        {
            if (t == typeof(int)) return "int";
            if (t == typeof(string)) return "string";
            if (t == typeof(float)) return "float";
            if (t == typeof(double)) return "double";
            if (t == typeof(long)) return "long";
            if (t == typeof(short)) return "short";
            if (t == typeof(byte)) return "byte";
            if (t == typeof(bool)) return "bool";
            return "global::" + t.FullName.Replace("+", ".");
        }

        private static string SanitizeIdentifier(string s)
        {
            if (string.IsNullOrEmpty(s)) return "_";
            var sb = new StringBuilder(s.Length);
            for (int i = 0; i < s.Length; i++)
            {
                var ch = s[i];
                bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_';
                sb.Append(ok ? ch : '_');
            }
            if (sb.Length == 0) return "_";
            if (sb[0] >= '0' && sb[0] <= '9') sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string EscapeStringLiteral(string s)
        {
            return s?.Replace("\\", "\\\\").Replace("\"", "\\\"") ?? string.Empty;
        }
    }
}
